# fly.toml app configuration file generated for data-transfer on 2023-10-05T12:36:55+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "data-transfer"
primary_region = "syd"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
